// create records for all the categories you listed, put them in an array of objects, and write a script to inject them into the database

const { default: axios } = require('axios');

const dummyItems = [{
    name: "To Kill a Mockingbird",
    description: "Harper Lee's classic novel about racial injustice in the Deep South.",
    price: 10,
    category: "Books & Media",
    author: "Harper Lee",
    images: ["to_kill_mockingbird_1.jpg", "to_kill_mockingbird_2.jpg"],
    stock: 120,
    averageRating: 4.9,
},
{
    name: "1984",
    description: "George Orwell's dystopian novel that delves into the dangers of totalitarianism.",
    price: 12,
    category: "Books & Media",
    author: "George Orwell",
    images: ["1984_book_1.jpg", "1984_book_2.jpg"],
    stock: 150,
    averageRating: 4.8,
},
{
    name: "Becoming",
    description: "Michelle Obama's memoir that explores her journey from the South Side of Chicago to the White House.",
    price: 18,
    category: "Books & Media",
    author: "Michelle Obama",
    images: ["becoming_1.jpg", "becoming_2.jpg"],
    stock: 90,
    averageRating: 4.9,
},
{
    name: "Sapiens: A Brief History of Humankind",
    description: "Yuval Noah Harari's exploration of the history of humankind from the Stone Age to the modern era.",
    price: 20,
    category: "Books & Media",
    author: "Yuval Noah Harari",
    images: ["sapiens_book_1.jpg", "sapiens_book_2.jpg"],
    stock: 100,
    averageRating: 4.8,
},
{
    name: "The Great Gatsby",
    description: "F. Scott Fitzgerald's classic novel set in the Jazz Age, exploring themes of wealth and ambition.",
    price: 8,
    category: "Books & Media",
    author: "F. Scott Fitzgerald",
    images: ["great_gatsby_1.jpg", "great_gatsby_2.jpg"],
    stock: 130,
    averageRating: 4.7,
},
{
    name: "Educated",
    description: "Tara Westover's memoir about growing up in a strict and abusive household in rural Idaho.",
    price: 16,
    category: "Books & Media",
    author: "Tara Westover",
    images: ["educated_1.jpg", "educated_2.jpg"],
    stock: 95,
    averageRating: 4.8,
},
{
    name: "Atomic Habits",
    description: "James Clear's guide to building good habits and breaking bad ones through small, incremental changes.",
    price: 15,
    category: "Books & Media",
    author: "James Clear",
    images: ["atomic_habits_1.jpg", "atomic_habits_2.jpg"],
    stock: 110,
    averageRating: 4.9,
},
{
    name: "Where the Crawdads Sing",
    description: "Delia Owens' novel about a young girl who grows up alone in the marshes of North Carolina.",
    price: 14,
    category: "Books & Media",
    author: "Delia Owens",
    images: ["crawdads_sing_1.jpg", "crawdads_sing_2.jpg"],
    stock: 120,
    averageRating: 4.8,
},
{
    name: "The Catcher in the Rye",
    description: "J.D. Salinger's novel that captures the teenage angst and alienation of its protagonist, Holden Caulfield.",
    price: 10,
    category: "Books & Media",
    author: "J.D. Salinger",
    images: ["catcher_rye_1.jpg", "catcher_rye_2.jpg"],
    stock: 140,
    averageRating: 4.7,
},
{
    name: "The Road",
    description: "Cormac McCarthy's post-apocalyptic novel about a father and son's journey across a desolate landscape.",
    price: 14,
    category: "Books & Media",
    author: "Cormac McCarthy",
    images: ["the_road_1.jpg", "the_road_2.jpg"],
    stock: 80,
    averageRating: 4.7,
},
{
    name: "Harry Potter and the Sorcerer's Stone",
    description: "J.K. Rowling's first book in the Harry Potter series, introducing readers to the world of magic.",
    price: 10,
    category: "Books & Media",
    author: "J.K. Rowling",
    images: ["harry_potter_1.jpg", "harry_potter_2.jpg"],
    stock: 200,
    averageRating: 4.9,
},
{
    name: "The Alchemist",
    description: "Paulo Coelho's allegorical novel about a young shepherd's journey to discover his personal legend.",
    price: 12,
    category: "Books & Media",
    author: "Paulo Coelho",
    images: ["the_alchemist_1.jpg", "the_alchemist_2.jpg"],
    stock: 100,
    averageRating: 4.8,
},
{
    name: "The Four Agreements",
    description: "Don Miguel Ruiz's guide to personal freedom and achieving happiness by following four simple agreements.",
    price: 10,
    category: "Books & Media",
    author: "Don Miguel Ruiz",
    images: ["four_agreements_1.jpg", "four_agreements_2.jpg"],
    stock: 120,
    averageRating: 4.8,
},
{
    name: "Brave New World",
    description: "Aldous Huxley's dystopian novel that explores a futuristic society where individuality is sacrificed for the sake of stability.",
    price: 14,
    category: "Books & Media",
    author: "Aldous Huxley",
    images: ["brave_new_world_1.jpg", "brave_new_world_2.jpg"],
    stock: 95,
    averageRating: 4.7,
},
{
    name: "Pride and Prejudice",
    description: "Jane Austen's classic novel that explores themes of love, class, and social expectations in 19th-century England.",
    price: 8,
    category: "Books & Media",
    author: "Jane Austen",
    images: ["pride_prejudice_1.jpg", "pride_prejudice_2.jpg"],
    stock: 150,
    averageRating: 4.8,
},
{
    name: "The Subtle Art of Not Giving a F*ck",
    description: "Mark Manson's no-nonsense guide to living a better life by focusing on what truly matters.",
    price: 14,
    category: "Books & Media",
    author: "Mark Manson",
    images: ["subtle_art_1.jpg", "subtle_art_2.jpg"],
    stock: 110,
    averageRating: 4.8,
},
{
    name: "The Power of Now",
    description: "Eckhart Tolle's spiritual guide to living in the present moment and achieving inner peace.",
    price: 15,
    category: "Books & Media",
    author: "Eckhart Tolle",
    images: ["power_of_now_1.jpg", "power_of_now_2.jpg"],
    stock: 100,
    averageRating: 4.9,
},
{
    name: "The Girl on the Train",
    description: "Paula Hawkins' psychological thriller about a woman who becomes embroiled in a missing person's investigation.",
    price: 12,
    category: "Books & Media",
    author: "Paula Hawkins",
    images: ["girl_on_train_1.jpg", "girl_on_train_2.jpg"],
    stock: 90,
    averageRating: 4.7,
},
{
    name: "Thinking, Fast and Slow",
    description: "Daniel Kahneman's exploration of the two systems that drive human thought: the fast, intuitive system and the slow, rational system.",
    price: 18,
    category: "Books & Media",
    author: "Daniel Kahneman",
    images: ["thinking_fast_slow_1.jpg", "thinking_fast_slow_2.jpg"],
    stock: 85,
    averageRating: 4.8,
},
{
    name: "The Book Thief",
    description: "Markus Zusak's novel set in Nazi Germany, following a young girl who finds solace in stealing books.",
    price: 14,
    category: "Books & Media",
    author: "Markus Zusak",
    images: ["book_thief_1.jpg", "book_thief_2.jpg"],
    stock: 120,
    averageRating: 4.9,
},
{
    name: "Outliers: The Story of Success",
    description: "Malcolm Gladwell's exploration of the factors that contribute to high levels of success.",
    price: 16,
    category: "Books & Media",
    author: "Malcolm Gladwell",
    images: ["outliers_1.jpg", "outliers_2.jpg"],
    stock: 100,
    averageRating: 4.8,
},
{
    name: "The Hobbit",
    description: "J.R.R. Tolkien's fantasy novel about Bilbo Baggins' adventure to reclaim a treasure guarded by a dragon.",
    price: 12,
    category: "Books & Media",
    author: "J.R.R. Tolkien",
    images: ["the_hobbit_1.jpg", "the_hobbit_2.jpg"],
    stock: 140,
    averageRating: 4.9,
},
{
    name: "The Fault in Our Stars",
    description: "John Green's novel about two teenagers who fall in love after meeting at a cancer support group.",
    price: 10,
    category: "Books & Media",
    author: "John Green",
    images: ["fault_in_stars_1.jpg", "fault_in_stars_2.jpg"],
    stock: 100,
    averageRating: 4.8,
},
{
    name: "The Art of War",
    description: "Sun Tzu's ancient Chinese military treatise that offers timeless advice on strategy and warfare.",
    price: 8,
    category: "Books & Media",
    author: "Sun Tzu",
    images: ["art_of_war_1.jpg", "art_of_war_2.jpg"],
    stock: 150,
    averageRating: 4.7,
},
{
    name: "Goodnight Moon",
    description: "Margaret Wise Brown's beloved children's book about a little bunny saying goodnight to everything in his room.",
    price: 6,
    category: "Books & Media",
    author: "Margaret Wise Brown",
    images: ["goodnight_moon_1.jpg", "goodnight_moon_2.jpg"],
    stock: 200,
    averageRating: 4.9,
},
{
    name: "The Intelligent Investor",
    description: "Benjamin Graham's classic book on value investing, teaching strategies for long-term financial success.",
    price: 18,
    category: "Books & Media",
    author: "Benjamin Graham",
    images: ["intelligent_investor_1.jpg", "intelligent_investor_2.jpg"],
    stock: 80,
    averageRating: 4.9,
},
{
    name: "Gone Girl",
    description: "Gillian Flynn's psychological thriller about a woman's mysterious disappearance and the secrets it uncovers.",
    price: 14,
    category: "Books & Media",
    author: "Gillian Flynn",
    images: ["gone_girl_1.jpg", "gone_girl_2.jpg"],
    stock: 90,
    averageRating: 4.7,
},
{
    name: "Little Fires Everywhere",
    description: "Celeste Ng's novel that explores the tensions in a suburban community after a controversial adoption.",
    price: 16,
    category: "Books & Media",
    author: "Celeste Ng",
    images: ["little_fires_1.jpg", "little_fires_2.jpg"],
    stock: 95,
    averageRating: 4.8,
},
{
    name: "The Hunger Games",
    description: "Suzanne Collins' dystopian novel about a televised fight to the death in a post-apocalyptic world.",
    price: 12,
    category: "Books & Media",
    author: "Suzanne Collins",
    images: ["hunger_games_1.jpg", "hunger_games_2.jpg"],
    stock: 130,
    averageRating: 4.9,
},
{
    name: "The Secret",
    description: "Rhonda Byrne's book on the power of positive thinking and the law of attraction.",
    price: 16,
    category: "Books & Media",
    author: "Rhonda Byrne",
    images: ["the_secret_1.jpg", "the_secret_2.jpg"],
    stock: 110,
    averageRating: 4.7,
},
{
    name: "The Night Circus",
    description: "Erin Morgenstern's fantasy novel about a magical competition between two young illusionists.",
    price: 15,
    category: "Books & Media",
    author: "Erin Morgenstern",
    images: ["night_circus_1.jpg", "night_circus_2.jpg"],
    stock: 80,
    averageRating: 4.8,
},
{
    name: "The Handmaid's Tale",
    description: "Margaret Atwood's dystopian novel about a society where women are stripped of their rights and used for reproduction.",
    price: 14,
    category: "Books & Media",
    author: "Margaret Atwood",
    images: ["handmaids_tale_1.jpg", "handmaids_tale_2.jpg"],
    stock: 90,
    averageRating: 4.9,
},
{
    name: "Moby Dick",
    description: "Herman Melville's epic tale of obsession and revenge as Captain Ahab hunts the elusive white whale.",
    price: 12,
    category: "Books & Media",
    author: "Herman Melville",
    images: ["moby_dick_1.jpg", "moby_dick_2.jpg"],
    stock: 100,
    averageRating: 4.7,
},
{
    name: "The Kite Runner",
    description: "Khaled Hosseini's novel about friendship, betrayal, and redemption in Afghanistan.",
    price: 14,
    category: "Books & Media",
    author: "Khaled Hosseini",
    images: ["kite_runner_1.jpg", "kite_runner_2.jpg"],
    stock: 110,
    averageRating: 4.8,
},
{
    name: "A Brief History of Time",
    description: "Stephen Hawking's exploration of the origins and structure of the universe, aimed at a general audience.",
    price: 16,
    category: "Books & Media",
    author: "Stephen Hawking",
    images: ["brief_history_time_1.jpg", "brief_history_time_2.jpg"],
    stock: 85,
    averageRating: 4.8,
},
{
    name: "The Silent Patient",
    description: "Alex Michaelides' psychological thriller about a woman who stops speaking after being accused of murdering her husband.",
    price: 14,
    category: "Books & Media",
    author: "Alex Michaelides",
    images: ["silent_patient_1.jpg", "silent_patient_2.jpg"],
    stock: 100,
    averageRating: 4.7,
},
{
    name: "The Stand",
    description: "Stephen King's post-apocalyptic novel about the survivors of a global pandemic and their struggle between good and evil.",
    price: 20,
    category: "Books & Media",
    author: "Stephen King",
    images: ["the_stand_1.jpg", "the_stand_2.jpg"],
    stock: 70,
    averageRating: 4.9,
},
{
    name: "Dune",
    description: "Frank Herbert's science fiction epic about a desert planet and the power struggle over its valuable resource, spice.",
    price: 18,
    category: "Books & Media",
    author: "Frank Herbert",
    images: ["dune_1.jpg", "dune_2.jpg"],
    stock: 95,
    averageRating: 4.9,
},];



const injectDummyData = () => {
    try {
        dummyItems.forEach(async (item) => {
            console.log(item);
            await axios.post('http://localhost:3040/api/products', item);
            console.log(item.name, " - was added");
        })

        console.log(dummyItems.length, ' - Dummy data successfully added!');
    } catch (error) {
        console.error('Error adding dummy data:', error);
    }
};

injectDummyData();